app/urls.py
# app/urls.py
# from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from app import views

urlpatterns = [
    #url(r'^$', views.HomePageView.as_view()),
    path('', views.home, name='home'),
    path('view1/', views.view1, name='view1'),
    path('search/', views.search, name='search'),
    path('view/<inc_num>', views.view_mgt, name='view_mgt'),
    path('view1/<inc_num>', views.view, name='view'),
    path('incident/', views.incident, name='incident'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

incident_web/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
# from django.conf.urls.static import static
urlpatterns = []

if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls),
                    # ..Put other stuff you want to be dev-only, etc...
                    ]

urlpatterns += [
    path('', include('app.urls')),
] 
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/forms.py
from functools import partial
from django import forms
from app import constants
from app.constants import Option, CompletionFlag, FlagState, CompletionStatus

FLAGS = [
    (CompletionFlag.未完了.value, CompletionFlag.未完了.name),
    (CompletionFlag.完了.value, CompletionFlag.完了.name),
    (CompletionFlag.すべて.value, CompletionFlag.すべて.name),
]

STATES = [
    (FlagState.ON.name, FlagState.ON.name),
    (FlagState.OFF.name, FlagState.OFF.name),
]

STATES_MENU = [
    (FlagState.ON.name, FlagState.ON.value),
    (FlagState.OFF.name, FlagState.OFF.value),
    (FlagState.ALL.name, FlagState.ALL.value),
]

COMPLETION_STATES = [
    (0, CompletionStatus.INCOMPLETE.value),
    (1, CompletionStatus.COMPLETE.value),
]

class HomeForm(forms.Form):
    date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    completion_flag = forms.CharField(
        widget=forms.Select(attrs={'style': 'height:30px; width:95px; background-color: white;'},
                            choices=FLAGS))
    flag_state = forms.CharField(
        widget=forms.Select(attrs={'style': 'height:30px; width:95px; background-color: white;'},
                            choices=STATES_MENU))

class IncidentForm(forms.Form):
    inc_num = forms.CharField(label='inc_num', max_length=13)

class IncidentDetailsForm(forms.Form):
    inc_num = forms.CharField(label='inc_num', required=False, max_length=13)  # インシデント番号
    inc_num_hidden = forms.CharField(label='inc_num_hidden', max_length=13,
                                     error_messages={'required': constants.INC_NUM_REQUIRED_ERR})
    user_name = forms.CharField(label='user_name', required=False, max_length=50,
                                error_messages={'max_length': constants.GEN_MAXLENGTH_ERR.format('顧客名', 50)})  # 顧客名
    system_name = forms.CharField(label='system_name', required=False, max_length=50,
                                  error_messages={
                                      'max_length': constants.GEN_MAXLENGTH_ERR.format('システム名', 50)})  # システム名
    occurrence_datetime = forms.CharField(label='occurrence_datetime', required=False, max_length=10,
                                          error_messages={
                                              'max_length': constants.GEN_MAXLENGTH_ERR.format('発生日時', 10)})  # 発生日時
    flag_state = forms.CharField(required=False,
                                 widget=forms.Select(  # フラグ状態
                                     attrs={'style': 'border-style: none; margin: 2px 0px 0px 2px; font-size: 14px; '
                                                     'width: 122px; height: 20px;'},
                                     choices=STATES))
    occurrence_event = forms.CharField(label='occurrence_event', required=False, max_length=4000,
                                       error_messages={
                                           'max_length': constants.GEN_MAXLENGTH_ERR.format('発生事象', 4000)})  # 発生事象
    business_impact = forms.CharField(label='business_impact', required=False, max_length=4000,
                                      error_messages={
                                          'max_length': constants.GEN_MAXLENGTH_ERR.format('業務影響', 4000)})  # 業務影響
    support_situation = forms.CharField(label='support_situation', required=False, max_length=4000,
                                        error_messages={
                                            'max_length': constants.GEN_MAXLENGTH_ERR.format('対応状況', 4000)})  # 対応状況
    next_action = forms.CharField(label='next_action', required=False, max_length=4000,
                                  error_messages={
                                      'max_length': constants.GEN_MAXLENGTH_ERR.format('次アクション', 4000)})  # 次アクション 
    cause = forms.CharField(label='cause', required=False, max_length=4000,
                            error_messages={'max_length': constants.GEN_MAXLENGTH_ERR.format('発生原因', 4000)})  # 発生原因
    provisional_measures = forms.CharField(label='provisional_measures', required=False, max_length=4000,
                                           error_messages={'max_length': constants.GEN_MAXLENGTH_ERR.format('対処（暫定）',
                                                                                                            4000)})  # 対処（暫定）
    cope = forms.CharField(label='cope', required=False, max_length=4000,
                           error_messages={'max_length': constants.GEN_MAXLENGTH_ERR.format('対処（恒久）', 4000)})  # 対処（恒久）
    completion_flag = forms.CharField(required=False,
                                      widget=forms.Select(  # 完了フラグ
                                          attrs={
                                              'style': 'border-style: none; margin: 2px 0px 0px 2px; font-size: 14px; '
                                                       'width: 122px; height: 20px;'},
                                          choices=COMPLETION_STATES))

app/templates/app/details.html
<!-- app/templates/details.html -->
<!DOCTYPE html>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap-4.0.0-dist/css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'app/jquery/css/jquery-ui.css' %}">
        <script src="{% static 'app/jquery/js/jquery-1.12.4.js' %}"></script> 
        <script src="{% static 'app/jquery/js/jquery-ui.js' %}"></script> 
        <script>
          $( function() {
            $( "#occurrence_datetime" ).datepicker({ dateFormat: 'yy/mm/dd' });
          } );
        </script>
    </head>
    <body>
        <div class="divMain">
            <div class="divTitle"><div class="divTop">クリティカルインシデント詳細</div></div>
            <form action="/incident/" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td class="table_td1">
                        <table cellspacing="0" cellpadding="0">
                            <tr>
                                <td><div class="divNumber colorSe"><div class="divTop">インシデント番号</div></div></td>
                                <td><div class="divInc2"><input class="inc2" type="text" id="inc_num" name="inc_num" value="{{ インシデント番号 }}" maxlength="13" disabled></input><input type="hidden" id="inc_num_hidden" name="inc_num_hidden" value="{{ インシデント番号 }}"></input></div></td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        {% if existing %}
                        <input class="exec" type="submit" value="更新" id="update" name="update"/>
                        {% endif %}
                        {% if not_existing %}
                        <input class="exec" type="submit" value="追加" id="add" name="add"/>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div>
                            {% if error_message %}<p class="error">&#9888;&nbsp;{{ error_message }}</p>{% endif %} 
                            {% if info_message %}<p class="info">&#x1F6C8;&nbsp;{{ info_message }}</p>{% endif %}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% if field.errors %}<p class="error">&#9888;&nbsp;{{ field.errors|striptags }}</p>{% endif %}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="divBorder">
                            <table class="table1">
                                <tr>
                                    <td>
                                        <table cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td><div class="divHead colorSe"><div class="divTop">顧客名</div></div></td>
                                                <td><div class="divText"><input class="name1" type="text" id="user_name" name="user_name" value="{{ 顧客名 }}" maxlength="50"></input></div></td>
                                            </tr>
                                        </table>
                                    </td>
                                    <td>
                                        <table cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td><div class="divHead divHead3 colorSe"><div class="divTop">システム名</div></div></td>
                                                <td><div class="divText"><input class="name1" type="text" id="system_name" name="system_name" value="{{ システム名 }}" maxlength="50"></input></div></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <table cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td><div class="divHead colorSe"><div class="divTop">発生日時</div></div></td>
                                                <td><div class="divText2"><input class="name2" type="text" id="occurrence_datetime" name="occurrence_datetime" value="{{ 発生日時 }}" maxlength="10"></input></div></td>
                                            </tr>
                                        </table>
                                    </td>
                                    <td>
                                        <table cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td><div class="divHead divHead3 colorSe"><div class="divTop">フラグ状態</div></div></td>
                                                <td><div class="divText2">{{ form.flag_state }}</div></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="divBorder2">
                            <table style="margin-left: 15px;" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td>
                                    <table cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td><div class="divHead2 colorSe"><div class="divTop">発生事象</div></div></td>
                                            <td colspan="3"><div class="area"><textarea class="area1" id="occurrence_event" name="occurrence_event" maxlength="4000">{{ 発生事象 }}</textarea></div></td>
                                        </tr>
                                        <tr>
                                            <td><div class="divHead2 colorSe"><div class="divTop">業務影響</div></div></td>
                                            <td colspan="3"><div class="area"><textarea class="area1" id="business_impact" name="business_impact" maxlength="4000">{{ 業務影響 }}</textarea></div></td>
                                        </tr>
                                        <tr>
                                            <td><div class="divHead4 colorSe"><div class="divTop">対応状況</div></div></td>
                                            <td colspan="3"><div class="area2"><textarea class="area2" id="support_situation" name="support_situation" maxlength="4000">{{ 対応状況 }}</textarea></div></td>
                                        </tr>
                                        <tr>
                                            <td><div class="divHead4 colorSe"><div class="divTop">次のアクション</div></div></td>
                                            <td colspan="3"><div class="area2"><textarea class="area2" id="next_action" name="next_action" maxlength="4000">{{ 次アクション }}</textarea></div></td>
                                        </tr>
                                        <tr>
                                            <td><div class="divHead2 colorSe"><div class="divTop">発生原因</div></div></td>
                                            <td colspan="3"><div class="area"><textarea class="area1" id="cause" name="cause" maxlength="4000">{{ 発生原因 }}</textarea></div></td>
                                        </tr>
                                        <tr>
                                            <td><div class="divHead2 colorSe"><div class="divTop">対処（暫定）</div></div></td>
                                            <td colspan="3"><div class="area"><textarea class="area1" id="provisional_measures" name="provisional_measures" maxlength="4000">{{ provisional_measures_val }}</textarea></div></td>
                                        </tr>
                                        <tr>
                                            <td><div class="divHead2 colorSe"><div class="divTop">対処（恒久）</div></div></td>
                                            <td colspan="3"><div class="area"><textarea class="area1" id="cope" name="cope" maxlength="4000">{{ cope_val }}</textarea></div></td>
                                        </tr>
                                        <tr>
                                            <td><div class="divHead5 colorSe"><div class="divTop">完了フラグ</div></div></td>
                                            <td colspan="3"><div class="divText2">{{ form.completion_flag }}</div></td>
                                        </tr>
                                    </table>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </td>
                </tr>
            </table>
            </form>
            <form action="/view1/" method="post">
                {% csrf_token %}
                <input class="exec2" type="submit" value="戻る" id="back" name="back"/>
            </form>
        </div>
    </body>
</html>

app/templates/app/home.html
<!-- app/templates/index.html -->
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="refresh" content="30"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap-4.0.0-dist/css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'app/jquery/css/jquery-ui.css' %}">
        <script src="{% static 'app/jquery/js/jquery-1.12.4.js' %}"></script> 
        <script src="{% static 'app/jquery/js/jquery-ui.js' %}"></script> 
        <script>
        $( function() {
            $( "#startDate" ).datepicker({ dateFormat: 'yy/mm/dd' });
            });
        $( function() {
            $( "#endDate" ).datepicker({ dateFormat: 'yy/mm/dd' });
            });
        
        $(document).ready(function() {
            //This will check the status of radio button onload
            $("#realtime").click(function() {
                $.datepicker._clearDate($( "#startDate" ));
                $.datepicker._clearDate($( "#endDate" ));
                $("#startDate").attr('disabled',true);
                $("#endDate").attr('disabled',true);
                $("#id_completion_flag").val(0); //SET TO INCOMPLETE
                $("#id_completion_flag").attr('disabled','disabled'); //DISABLE
            });
            $("#periodic").click(function() {
                $("#startDate").attr('disabled',false);
                $("#endDate").attr('disabled',false);
                $("#id_completion_flag").removeAttr('disabled','disabled'); //ENABLE DROPDOWN
            });
        });
        </script>
    </head>
    <body>
        <div class="divMain">
            <div class="divTitle2"><div class="divTop">クリティカルインシデント一覧</div></div>
            <form action="/" method="post">
            {% csrf_token %}
            <table class="errHomeTable" cellspacing="0" cellpadding="0">
                <tr>
                    <td colspan="2">
                        <div>
                            {% if error_message %}<p class="error">&#9888;&nbsp;{{ error_message }}</p>{% endif %} 
                            {% if info_message %}<p class="info">&#x1F6C8;&nbsp;{{ info_message }}</p>{% endif %}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% if field.errors %}<p class="error">&#9888;&nbsp;{{ field.errors|striptags }}</p>{% endif %}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </td>
                </tr>
            </table>
            <div class="divBorder4">
                <table class="table table-striped2 tablePg1 tableStyle"><!--tablePg1-->
                    <thead class="thhead tHead1 tabletd1">
                    <tr>
                        <th scope="col" class="tableth1" style="width: 117px; font-size: 14px; vertical-align: middle;">インシデント番号</th>
                        <th scope="col" class="tableth1" style="width: 85px; font-size: 14px; vertical-align: middle;">ユーザ名</th>
                        <th scope="col" class="tableth1" style="width: 85px; font-size: 14px; vertical-align: middle;">システム名</th>
                        <th scope="col" class="tableth1" style="width: 170px; font-size: 14px; vertical-align: middle;">発生事象</th>
                        <th scope="col" class="tableth1" style="width: 170px; font-size: 14px; vertical-align: middle;">次のアクション</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for inc in incidents %}
                    <tr>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1"><a href="{% url 'view_mgt' inc.インシデント番号 %}">{{ inc.インシデント番号 }}</a></div></td>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1">{{ inc.顧客名 }}</div></td>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1">{{ inc.システム名 }}</div></td>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1">{{ inc.発生事象|truncatechars:45 }}</div></td>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1">{{ inc.次アクション|truncatechars:45 }}</div></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            </form>
        </div>    
    </body>
</html>

app/templates/app/search.html
<!-- app/templates/index.html -->
<!DOCTYPE html>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">

<html>
    <head>
<!--        <meta charset="utf-8">-->
<!--        <title></title>-->
    </head>
    <body>
        <div class="divMain">
            <div class="divTitle"><div class="divTop">クリティカルインシデント詳細記入</div></div>
            <form action="/incident/" method="post"> 
            {% csrf_token %}
            <table>
                <tr>
                    <td style="width: 448px;">
                        <table cellspacing="0" cellpadding="0">
                            <tr>
                                <td><div class="divNumber colorSe"><div class="divTop">インシデント番号</div></div></td>
                                <td><div class="divInc"><input class="inc" type="text" id="inc_num" name="inc_num" value="{{inc_num}}" maxlength="13"></input></div></td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        <input class="exec" type="submit" value="実行" id="search"/>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div>
                            {% if error_message %}<p class="error">&#9888;&nbsp;{{ error_message }}</p>{% endif %} 
                            {% if info_message %}<p class="info">&#x1F6C8;&nbsp;{{ info_message }}</p>{% endif %}
                        </div>
                    </td>
                </tr>
            </table>
            </form>
            <form action="/view1/" method="post">
                {% csrf_token %}
                <input class="back1" type="submit" value="戻る" id="back" name="back"/>
            </form>
        </div>    
    </body>
</html>

app/templates/app/view1.html
<!-- app/templates/index.html -->
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap-4.0.0-dist/css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'app/jquery/css/jquery-ui.css' %}">
        <script src="{% static 'app/jquery/js/jquery-1.12.4.js' %}"></script> 
        <script src="{% static 'app/jquery/js/jquery-ui.js' %}"></script> 
        <script>
        $( function() {
            $( "#startDate" ).datepicker({ dateFormat: 'yy/mm/dd' });
            });
        $( function() {
            $( "#endDate" ).datepicker({ dateFormat: 'yy/mm/dd' });
            });
        
        $(document).ready(function() {
            //This will check the status of radio button onload
            $("#realtime").click(function() {
                $.datepicker._clearDate($( "#startDate" ));
                $.datepicker._clearDate($( "#endDate" ));
                $("#startDate").attr('disabled',true);
                $("#endDate").attr('disabled',true);
                $("#id_completion_flag").val(0); //SET TO INCOMPLETE
                $("#id_completion_flag").attr('disabled','disabled'); //DISABLE
                $("#id_flag_state").val('ALL'); //SET TO INCOMPLETE
                $("#id_flag_state").attr('disabled','disabled'); //DISABLE
            });
            $("#periodic").click(function() {
                $("#startDate").attr('disabled',false);
                $("#endDate").attr('disabled',false);
                $("#id_completion_flag").removeAttr('disabled','disabled'); //ENABLE DROPDOWN
                $("#id_flag_state").removeAttr('disabled','disabled'); //ENABLE DROPDOWN
            });
        });
        </script>
    </head>
    <body>
        <div class="divMain">
            <div class="divTitle"><div class="divTop">クリティカルインシデント一覧</div></div>
            <form action="/view1/" method="post">
            {% csrf_token %}
            <table cellspacing="0" cellpadding="0">
                <tr>
                    <td colspan="2" style="width: 1020px;">
                        <table cellspacing="0" cellpadding="0">
                            <tr>
                                <td>
                                    <div class="divOptionPanel1">
                                        <label class="lblOption1"><input {% ifequal option_filter 0 %} checked='checked' {% endifequal %} type="radio" name="option_filter" id="realtime" value="0">&nbsp;リアルタイム表示</label>
                                        <label class="lblOption1"><input {% ifequal option_filter 1 %} checked='checked' {% endifequal %} type="radio" name="option_filter" id="periodic" value="1">&nbsp;期間表示</label>
                                    </div>
                                </td>
                                <td><div class="divDDTitle1">完了フラグ：</div></td>
                                <td><div class="divDDTitle1">フラグ状態：</div></td>
                                <td colspan="2"></td>
                            </tr>
                            <tr>
                                <td width="380px"><div class="divDate1"><div class="divTop3">抽出期間</div></div>
                                    <div class="divDate2">
                                        <div class="divTop2"><input {% ifequal option_filter 0 %} disabled {% endifequal %} class="inc3" type="text" id="startDate" name="startDate" placeholder="yyyy/mm/dd" value="{{ startDate }}"/>
                                        </div>
                                    </div>
                                    <div class="divDate3">～</div>
                                    <div class="divDate2">
                                        <div class="divTop2"><input {% ifequal option_filter 0 %} disabled {% endifequal %} class="inc3" type="text" id="endDate" name="endDate" placeholder="yyyy/mm/dd" value="{{ endDate }}"/>
                                        </div>
                                    </div>
                                </td>
                                <td width="110px">
                                    <div class="dropdown1">{{ form.completion_flag }}</div></td>
                                <td width="135px">
                                    <div class="dropdown1">{{ form.flag_state }}</div>
                                </td>
                                <td width="200px"><input class="main1" type="submit" value="画面リフレッシュ" id="refresh" name="refresh" />
                                </td>
                                <td><button class="main" type="submit" value="新規入力/更新画面" id="search" name="search">新規入力/更新画面</button>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div>
                            {% if error_message %}<p class="error">&#9888;&nbsp;{{ error_message }}</p>{% endif %} 
                            {% if info_message %}<p class="info">&#x1F6C8;&nbsp;{{ info_message }}</p>{% endif %}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% if field.errors %}<p class="error">&#9888;&nbsp;{{ field.errors|striptags }}</p>{% endif %}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </td>
                </tr>
            </table>
            <div class="divBorder3">
                <table class="table table-striped tablePg1 tableStyle"><!--tablePg1-->
                    <thead class="thhead1 tHead1 tabletd1">
                    <tr>
                        <th scope="col" class="tableth1" style="width: 117px; font-size: 14px; vertical-align: middle;">インシデント番号</th>
                        <th scope="col" class="tableth1" style="width: 85px; font-size: 14px; vertical-align: middle;">ユーザ名</th>
                        <th scope="col" class="tableth1" style="width: 85px; font-size: 14px; vertical-align: middle;">システム名</th>
                        <th scope="col" class="tableth1" style="width: 170px; font-size: 14px; vertical-align: middle;">発生事象</th>
                        <th scope="col" class="tableth1" style="width: 170px; font-size: 14px; vertical-align: middle;">次のアクション</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for inc in incidents %}
                    <tr>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1"><a href="{% url 'view' inc.インシデント番号 %}">{{ inc.インシデント番号 }}</a></div></td>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1">{{ inc.顧客名 }}</div></td>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1">{{ inc.システム名 }}</div></td>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1">{{ inc.発生事象|truncatechars:45 }}</div></td>
                        <td class="tabletd1" style="vertical-align: text-top !important;"><div class="tableDiv1">{{ inc.次アクション|truncatechars:45 }}</div></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            </form>
        </div>    
    </body>
</html>